/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProgressRecord = IDL.Record({
  'moduleId' : IDL.Text,
  'completedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'score' : IDL.Nat,
  'tradeId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'currentTradeId' : IDL.Text,
  'onboardingCompleted' : IDL.Bool,
});
export const PathwayEnrollment = IDL.Record({
  'completedModules' : IDL.Vec(IDL.Text),
  'pathwayId' : IDL.Text,
  'userId' : IDL.Principal,
  'tradeId' : IDL.Text,
  'enrolledAt' : IDL.Int,
});
export const QuizResult = IDL.Record({
  'completedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'quizId' : IDL.Text,
});
export const SavedAnswer = IDL.Record({
  'userId' : IDL.Principal,
  'answer' : IDL.Text,
  'questionId' : IDL.Text,
  'savedAt' : IDL.Int,
});
export const SkillAssessment = IDL.Record({
  'assessedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'level' : IDL.Text,
  'tradeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSavedAnswers' : IDL.Func([], [], []),
  'completeModule' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [ProgressRecord],
      [],
    ),
  'completeOnboarding' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'enrollInPathway' : IDL.Func([IDL.Text, IDL.Text], [PathwayEnrollment], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(PathwayEnrollment)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyProgress' : IDL.Func([], [IDL.Vec(ProgressRecord)], ['query']),
  'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getMySavedAnswers' : IDL.Func([], [IDL.Vec(SavedAnswer)], ['query']),
  'getMySkillAssessments' : IDL.Func([], [IDL.Vec(SkillAssessment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordQuizResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [QuizResult], []),
  'saveAnswer' : IDL.Func([IDL.Text, IDL.Text], [SavedAnswer], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSkillAssessment' : IDL.Func([IDL.Text, IDL.Text], [SkillAssessment], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProgressRecord = IDL.Record({
    'moduleId' : IDL.Text,
    'completedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'score' : IDL.Nat,
    'tradeId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'currentTradeId' : IDL.Text,
    'onboardingCompleted' : IDL.Bool,
  });
  const PathwayEnrollment = IDL.Record({
    'completedModules' : IDL.Vec(IDL.Text),
    'pathwayId' : IDL.Text,
    'userId' : IDL.Principal,
    'tradeId' : IDL.Text,
    'enrolledAt' : IDL.Int,
  });
  const QuizResult = IDL.Record({
    'completedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'quizId' : IDL.Text,
  });
  const SavedAnswer = IDL.Record({
    'userId' : IDL.Principal,
    'answer' : IDL.Text,
    'questionId' : IDL.Text,
    'savedAt' : IDL.Int,
  });
  const SkillAssessment = IDL.Record({
    'assessedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'level' : IDL.Text,
    'tradeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSavedAnswers' : IDL.Func([], [], []),
    'completeModule' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [ProgressRecord],
        [],
      ),
    'completeOnboarding' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'enrollInPathway' : IDL.Func([IDL.Text, IDL.Text], [PathwayEnrollment], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(PathwayEnrollment)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyProgress' : IDL.Func([], [IDL.Vec(ProgressRecord)], ['query']),
    'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getMySavedAnswers' : IDL.Func([], [IDL.Vec(SavedAnswer)], ['query']),
    'getMySkillAssessments' : IDL.Func(
        [],
        [IDL.Vec(SkillAssessment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordQuizResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [QuizResult],
        [],
      ),
    'saveAnswer' : IDL.Func([IDL.Text, IDL.Text], [SavedAnswer], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSkillAssessment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [SkillAssessment],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };