/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PathwayEnrollment {
  'completedModules' : Array<string>,
  'pathwayId' : string,
  'userId' : Principal,
  'tradeId' : string,
  'enrolledAt' : bigint,
}
export interface ProgressRecord {
  'moduleId' : string,
  'completedAt' : bigint,
  'userId' : Principal,
  'score' : bigint,
  'tradeId' : string,
}
export interface QuizResult {
  'completedAt' : bigint,
  'userId' : Principal,
  'score' : bigint,
  'totalQuestions' : bigint,
  'quizId' : string,
}
export interface SavedAnswer {
  'userId' : Principal,
  'answer' : string,
  'questionId' : string,
  'savedAt' : bigint,
}
export interface SkillAssessment {
  'assessedAt' : bigint,
  'userId' : Principal,
  'level' : string,
  'tradeId' : string,
}
export interface UserProfile {
  'displayName' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'email' : string,
  'currentTradeId' : string,
  'onboardingCompleted' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearSavedAnswers' : ActorMethod<[], undefined>,
  'completeModule' : ActorMethod<
    [string, string, string, bigint],
    ProgressRecord
  >,
  'completeOnboarding' : ActorMethod<[string], boolean>,
  'createOrUpdateProfile' : ActorMethod<[string, string], UserProfile>,
  'enrollInPathway' : ActorMethod<[string, string], PathwayEnrollment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyEnrollments' : ActorMethod<[], Array<PathwayEnrollment>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyProgress' : ActorMethod<[], Array<ProgressRecord>>,
  'getMyQuizResults' : ActorMethod<[], Array<QuizResult>>,
  'getMySavedAnswers' : ActorMethod<[], Array<SavedAnswer>>,
  'getMySkillAssessments' : ActorMethod<[], Array<SkillAssessment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordQuizResult' : ActorMethod<[string, bigint, bigint], QuizResult>,
  'saveAnswer' : ActorMethod<[string, string], SavedAnswer>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSkillAssessment' : ActorMethod<[string, string], SkillAssessment>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];